# Generated by Django 3.2.9 on 2021-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_rename_programmes_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_name',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='programme',
            name='img_name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
