# Generated by Django 3.2.9 on 2021-11-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20211116_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img_name',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='img_name',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=0, upload_to='media'),
        ),
        migrations.AddField(
            model_name='programme',
            name='photo',
            field=models.ImageField(default=0, upload_to='media'),
        ),
    ]
