# Generated by Django 3.2.7 on 2021-11-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20211116_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=0, upload_to='media/materials'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='photo',
            field=models.ImageField(default=0, upload_to='media/posts'),
        ),
    ]
